name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Auth Service Docker Build
      - name: Build AuthService Docker Image
        run: |
          docker build -t authservice:latest ./AuthService

      # Book Service Docker Build
      - name: Build BookService Docker Image
        run: |
          docker build -t bookservice:latest ./BookService

      # Borrow Service Docker Build
      - name: Build BorrowService Docker Image
        run: |
          docker build -t borrowservice:latest ./BorrowService

      # API Gateway Docker Build
      - name: Build ApiGateway Docker Image
        run: |
          docker build -t apigateway:latest ./ApiGateway