name: Build and deploy ASP.Net Core app to Azure Web App - auth-service-v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./AuthService/AuthService.csproj

      - name: Build project
        run: dotnet build ./AuthService/AuthService.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./AuthService/AuthService.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'auth-service-v2'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AUTH_SERVICE }}
          package: publish