name: Build and deploy ASP.Net Core app to Azure Web App - book-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./BookService/BookService.csproj

      - name: Build project
        run: dotnet build ./BookService/BookService.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./BookService/BookService.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'book-service'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: publish